include:
  - project: 'gzdkh/infra/DKH.Infrastructure'
    file: '/ci-cd/gitlab/dotnet-service.gitlab-ci.yml'

variables:
  COMPOSE_SERVICE_NAME: "api-management-service"
  NUGET_PROJECT_ID: "79414535"
