<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Grpc.Tools">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="DKH.Platform.Grpc.Common"/>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="proto/api_management/api/api_key_crud/v1/api_keys_crud_service.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/api/api_key_query/v1/api_key_query_service.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/api/api_key_usage/v1/api_key_usage_service.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/models/api_key/v1/api_key.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/models/api_key_usage/v1/api_key_usage.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/models/ai_provider/v1/ai_provider.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/api/ai_provider_crud/v1/ai_provider_crud_service.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/models/module/v1/module.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/api/module_catalog/v1/module_catalog_service.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/api/module_state/v1/module_state_service.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
    <Protobuf Include="proto/api_management/api/module_entitlement/v1/module_entitlement_service.proto" ProtoRoot="proto" AdditionalProtocArguments="--proto_path=$(DKHPlatformGrpcCommonProtoDir)"/>
  </ItemGroup>
</Project>
